name: Deploy OpenTelemetry Demo to EKS

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/component-build-images.yml

  test:
    needs: build
    uses: ./.github/workflows/run-integration-tests.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test, build
    env:
      EKS_CLUSTER_NAME: ENPM818-final-proj-cluster-uw2
      AWS_REGION: us-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Congifure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}
  
      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Check pods pre-deployment
        run: |
          kubectl get pods

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./kubernetes/opentelemetry-demo.yaml
      
      - name: Check pods after-deployment
        run: |
          kubectl get pods


